# users


### getAll
GET http://localhost:3000/users/fa/fae


### add
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Manh Thai"
}


### get
GET http://localhost:3000/users/1


### remove
DELETE http://localhost:3000/users/65d5bd22b1e8a25d01b9c3bf


### set
PATCH http://localhost:3000/users/65d5bc4ae519a3411c701ef1
Content-Type: application/json

{
    "name": "math-ezdev"
}
